### ISSUE TITLE
once errors on manage display Drupal pages

### ISSUE THREAD

**Issue by BrianGilbert** [druxt/cms.druxtjs.org#7]
**Describe the bug**
If you try to 'Manage Display' or 'Manage Form Display' there will be errors logged to console, and you are unable to drag the fields into desired order.

This is related to gin theme and there is an open issue about it https://www.drupal.org/project/gin/issues/3204589

**To Reproduce**
1. Go to `/admin/structure/types/manage/article/display`
2. Check console
3. See error

**Expected behavior**
Widget to drag fields around should be displayed

**Comment by Decipher** [comment]
Issue appears to be resolved.
